steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "${_GCR_HOSTNAME}/${_PROJECT_ID}/${_SERVICE_NAME}:latest"
      - .
      - "-f"
      - Dockerfile
    id: Build

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "${_GCR_HOSTNAME}/${_PROJECT_ID}/${_SERVICE_NAME}:latest"
    id: Push

  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image=${_GCR_HOSTNAME}/${_PROJECT_ID}/${_SERVICE_NAME}:latest
      - --region=${_DEPLOY_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --port=80
    id: Deploy

substitutions:
  _DEPLOY_REGION: asia-southeast1
  _GCR_HOSTNAME: asia.gcr.io
  _SERVICE_NAME: euroautoparts-landing-page
  _PROJECT_ID: euroautoparts-landing-page
